import './globals.css'
import { Inter } from 'next/font/google'
import { MainNav } from "@/components/dashboard/main-nav"
import { Button } from "@/components/ui/button"



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b sticky top-0 bg-white z-[100]">
          <div className="flex h-16 items-center px-4">
            <MainNav className="mx-6" />
            <div className="ml-auto flex items-center space-x-4">
              <Button>
                Log out
              </Button>
            </div>
          </div>
        </div>
        {children}  
      </body>
    </html>
  )
}
